### ISSUE TITLE
package.json does not have react-atom-fork as a dependency

### ISSUE THREAD

**Issue by driskell** [atom/reactionary#4]
git-blame package has stopped working for me (alexcorre/git-blame#83)

Turns out that it uses this package (though it's called `reactionary-atom-fork`) but this package does not list `react-atom-fork` as a dependency.

When module cache is generated it doesn't bother logging folders for this module as ones that should use the cache because it has no dependencies and it does not expect it to call `require`

So what we have is, when this module calls `require`, it ignores Atom module cache; when other modules and other packages call `require`, it does not. And in the case of `git-blame` for me - it loads two completely different installations of the `react-atom-fork` module which conflict and break the package.

**Comment by driskell** [comment]
Location in Atom module cache code where this module is skipped is:

https://github.com/atom/atom/blob/master/src/module-cache.coffee#L101

**Comment by driskell** [comment]
Hi @nathansobo - sorry for the ping - is this something due to be looked at? Or should git-blame cease using it?

**Comment by nathansobo** [comment]
I don't think you should use it. It's designed to be used with a React dependency from the parent application. But it's a tiny wrapper and you could just copy and paste the pieces of it that are useful to you and move on. There are also JSX extensions for CoffeeScript now, which might be worth a look.

**Comment by driskell** [comment]
Thanks @nathansobo - so is that to say, the missing dependency will not be added, and this project is closed?

**Comment by nathansobo** [comment]
The dependency is left out intentionally so you can use whatever version of React you want by including React as a sibling dependency of this library in your project. It will look upward to the parent directory and find it. But, yeah, I also won't really be maintaining this library. There's not much to it though so if you manage the dependency as I described, it should work fine.

**Comment by driskell** [comment]
@nathansobo The problem, however, is when used in an Atom package. I'm curious on your thoughts on this!

When used as an Atom package, Atom sees it has zero dependencies and does not log its path in the paths that should use the Atom module cache. So all require calls (which Atom assumes it never does) will bypass the module cache.

Problem begins because Atom has react. So when module cache is hit for a package, even though the package might have its own react in its node_modules, the Atom module cache kicks in and returns the same one Atom uses. Makes sense, as it prevents duplication.

However, when reactionary calls require - because its path is not in the module cache paths (because Atom thinks it doesn't need to as it doesn't have any dependencies) - the call to require bypasses the module cache, and iterates upwards - eventually hitting the react in the package's own node_modules. Chances are these are identical versions.

Now we have two instances of react loaded. The Atom instance. The package instance. Both same version.

Package then uses reactionary and actually reactionary returns components that are created using instances of a different React to that which Atom and the package itself is using. So essentially the reactionary values are not compatible - react in render() checks the result is "instanceof" something - and this check fails - it's an "instanceof" the right thing but the wrong instance.

**Comment by nathansobo** [comment]
I'd recommend copying and pasting the code from this library into your package as a workaround for now if you still want to use the syntactic sugar it provides.
